<?php
	$y=0;
	$apps[$x]['menu'][$y]['title']['en-us'] = "Billing";
	$apps[$x]['menu'][$y]['title']['id'] = "Billing";
	$apps[$x]['menu'][$y]['uuid'] = "9a3b4c5d-6e7f-8a0b-1c2d-3e4f5a6b7c8d";
	$apps[$x]['menu'][$y]['parent_uuid'] = "fd29e39c-c936-f5fc-8e2b-611681b266b5";
	$apps[$x]['menu'][$y]['category'] = "internal";
	$apps[$x]['menu'][$y]['path'] = "/app/billing/billing.php";
	$apps[$x]['menu'][$y]['groups'][] = "admin";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['menu'][$y]['title']['en-us'] = "Rates";
	$apps[$x]['menu'][$y]['title']['id'] = "Tarif";
	$apps[$x]['menu'][$y]['uuid'] = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d";
	$apps[$x]['menu'][$y]['parent_uuid'] = "9a3b4c5d-6e7f-8a0b-1c2d-3e4f5a6b7c8d";
	$apps[$x]['menu'][$y]['category'] = "internal";
	$apps[$x]['menu'][$y]['path'] = "/app/billing/billing_rates.php";
	$apps[$x]['menu'][$y]['groups'][] = "admin";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['menu'][$y]['title']['en-us'] = "Reports";
	$apps[$x]['menu'][$y]['title']['id'] = "Laporan";
	$apps[$x]['menu'][$y]['uuid'] = "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e";
	$apps[$x]['menu'][$y]['parent_uuid'] = "9a3b4c5d-6e7f-8a0b-1c2d-3e4f5a6b7c8d";
	$apps[$x]['menu'][$y]['category'] = "internal";
	$apps[$x]['menu'][$y]['path'] = "/app/billing/billing_report.php";
	$apps[$x]['menu'][$y]['groups'][] = "admin";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
$y++;
$apps[$x]['menu'][$y]['title']['en-us'] = "Invoice";
$apps[$x]['menu'][$y]['title']['id'] = "Invoice";
$apps[$x]['menu'][$y]['uuid'] = "3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f";
$apps[$x]['menu'][$y]['parent_uuid'] = "9a3b4c5d-6e7f-8a0b-1c2d-3e4f5a6b7c8d";
$apps[$x]['menu'][$y]['category'] = "internal";
$apps[$x]['menu'][$y]['path'] = "/app/billing/billing_invoice.php";
$apps[$x]['menu'][$y]['groups'][] = "admin";
$apps[$x]['menu'][$y]['groups'][] = "superadmin";
$y++;
$apps[$x]['menu'][$y]['title']['en-us'] = "Call Types";
$apps[$x]['menu'][$y]['title']['id'] = "Tipe Panggilan";
$apps[$x]['menu'][$y]['uuid'] = "4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a";
$apps[$x]['menu'][$y]['parent_uuid'] = "9a3b4c5d-6e7f-8a0b-1c2d-3e4f5a6b7c8d";
$apps[$x]['menu'][$y]['category'] = "internal";
$apps[$x]['menu'][$y]['path'] = "/app/billing/billing_call_types.php";
$apps[$x]['menu'][$y]['groups'][] = "admin";
$apps[$x]['menu'][$y]['groups'][] = "superadmin";
?>
